## Numpy: Number Python

In [298]:
#not numpy
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [299]:
#import numpy
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [300]:
np.array([np.pi,4,2,3])

array([3.14159265, 4.        , 2.        , 3.        ])

In [301]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [302]:
np.array([1,2,'a'])

array(['1', '2', 'a'], dtype='<U11')

In [303]:
#multidimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Create arrays from scratch

In [304]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [305]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [306]:
p = np.ones([2, 3], int) #integers
p

array([[1, 1, 1],
       [1, 1, 1]])

In [307]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [308]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 10, stepping by 2
print(np.arange(0, 10, 1))

# compared to the built-in range() function
print(list(range(0,10)))

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [309]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [310]:
#repeat
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [311]:
#this also works
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## Distribution generator

In [312]:
# uniformly distributed
# random values between 0 and 1
np.random.random(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [313]:
np.random.random((2,4)) #specify the shape

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ]])

In [314]:
# normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.61980106,  1.79116846,  0.17100044],
       [-1.72567135,  0.16065854, -0.85898532],
       [-0.20642094,  0.48842647, -0.83833097]])

In [315]:
# random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 6, 0],
       [6, 3, 3],
       [8, 8, 8]])

In [316]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [317]:
# Create an uninitialized array of given shape and type
# `empty`, unlike `zeros`, does not set the array values to zero,
# and may therefore be marginally faster.
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Numpy data types
Data Type Description <br>
bool_ Boolean (True or False) stored as a byte <br>
int_ Default integer type (same as C long; normally either int64 or int32) <br>
intc Identical to C int (normally int32 or int64) <br>
intp Integer used for indexing (same as C ssize_t; normally either int32 or int64) <br>
int8 Byte (–128 to 127) <br>
int16 Integer (–32768 to 32767) <br>
int32 Integer (–2147483648 to 2147483647) <br>
int64 Integer (–9223372036854775808 to 9223372036854775807) <br>
uint8 Unsigned integer (0 to 255) <br>
uint16 Unsigned integer (0 to 65535) <br>
uint32 Unsigned integer (0 to 4294967295) <br>
uint64 Unsigned integer (0 to 18446744073709551615) <br>
float_ Shorthand for float64 <br>
float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa <br>
float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa <br>
float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa <br>
complex_ Shorthand for complex128 <br>
complex64 Complex number, represented by two 32-bit floats <br>
complex128 Complex number, represented by two 64-bit floats <br>

## Attributes of arrays
Determining the size, shape, memory consumption, and data types of arrays

In [318]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [319]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [320]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## Indexing of arrays
Getting and setting the value of individual array elements

In [321]:
print(x1)

[5 0 3 3 7 9]


In [322]:
print(x1[0])
print(x1[4])
print(x1[-1])
print(x1[-2])

5
7
9
7


In [323]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [324]:
x2[0,0]

3

In [325]:
x2[0,-1]

4

In [326]:
#mutable
x2[0,0] = 9
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [327]:
#unchanged type; modified values

In [328]:
x1[0]=np.pi
x1

array([3, 0, 3, 3, 7, 9])

## Slicing of arrays
Getting and setting smaller subarrays within a larger array

In [329]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [330]:
x[:5] # first five elements; not include index 5(6th)

array([0, 1, 2, 3, 4])

In [331]:
x[5:] # elements since index 5(6th)

array([5, 6, 7, 8, 9])

In [332]:
x[4:7] 

array([4, 5, 6])

In [333]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [334]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [335]:
x[1::3]

array([1, 4, 7])

In [336]:
x[1::1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [337]:
x[:-1] # does not include -1, the last one

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [338]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [339]:
x[5::-1] # reversed from index 5

array([5, 4, 3, 2, 1, 0])

In [340]:
x[5:-1] # normal order

array([5, 6, 7, 8])

In [341]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [342]:
x[7::-3] # reversed every 3 from index 7

array([7, 4, 1])

### slicing of multidimensional arrays

In [343]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [344]:
x2[0:2,0:3] # two rows, three columns

array([[9, 5, 2],
       [7, 6, 8]])

In [345]:
x2[:2,:3]

array([[9, 5, 2],
       [7, 6, 8]])

In [346]:
x2[:, ::2] # all rows, every other column

array([[9, 2],
       [7, 8],
       [1, 7]])

In [347]:
x2[::-1,::-1] #reverse 

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 9]])

In [348]:
x2[:,0]

array([9, 7, 1])

In [349]:
#in row access, column can be omitted; NOT vice versa
print(x2[0,]) # equivalent to x2[0, :]

[9 5 2 4]


In [350]:
# x2[,0]

In [351]:
x2

array([[9, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [352]:
x2 > 5

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [353]:
#conditional indexing
x2[x2 > 5]

array([9, 7, 6, 8, 8, 6, 7, 7])

In [354]:
x2[x2 > 5] = 0
x2

array([[0, 5, 2, 4],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [355]:
x2[x2 == 5]

array([5])

In [356]:
x2[x2 != 5]

array([0, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

In [357]:
x2[x2 > 5]

array([], dtype=int32)

In [358]:
x2[x2 >= 5]

array([5])

In [359]:
x2[x2 < 5]

array([0, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

In [360]:
x2[x2 <= 5]

array([0, 5, 2, 4, 0, 0, 0, 0, 1, 0, 0, 0])

### No copy views of subarrays

In [361]:
x2

array([[0, 5, 2, 4],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [362]:
x2_sub = x2[:2, :2]
x2_sub

array([[0, 5],
       [0, 0]])

In [363]:
x2_sub[0, 0] = 100
x2_sub

array([[100,   5],
       [  0,   0]])

In [364]:
x2

array([[100,   5,   2,   4],
       [  0,   0,   0,   0],
       [  1,   0,   0,   0]])

In [365]:
#use copy() to actually copy
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = -20
x2_sub_copy

array([[-20,   5],
       [  0,   0]])

In [366]:
x2

array([[100,   5,   2,   4],
       [  0,   0,   0,   0],
       [  1,   0,   0,   0]])

## Reshaping of arrays
Changing the shape of a given array

In [367]:
#reshape()
g = np.arange(1, 10)
grid = g.reshape(3,3)
print(g)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [368]:
### size match
# g.reshape(2,3)

In [369]:
#no-copy view
grid[1,1] = 100
print(grid)
print(g)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
[  1   2   3   4 100   6   7   8   9]


In [370]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [371]:
# row vector via reshape
# dimension
x.reshape((1,3))

array([[1, 2, 3]])

In [372]:
#resize() 
gg = np.arange(0, 9)
gg

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [373]:
gg.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [374]:
gg.resize(3,3)
gg

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [375]:
x

array([1, 2, 3])

In [376]:
# row vector via newaxis
x[np.newaxis,:] 
x[np.newaxis,]

array([[1, 2, 3]])

In [377]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [378]:
# column vector via reshape
x = np.arange(0,6)
x.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [379]:
x

array([0, 1, 2, 3, 4, 5])

In [380]:
x[::2, np.newaxis]

array([[0],
       [2],
       [4]])

## Concatenating and splitting of arrays
Combining multiple arrays into one, and splitting one array into many

In [381]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [382]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [383]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [384]:
# concatenate along the first axis (zero-indexed)
np.concatenate([grid, grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [385]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [386]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [387]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [388]:
#pass a list of indices giving the split point
x = [1, 2, 3, 99, 99, 3, 2, 1, 1, 2, 3]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1 1 2 3]


In [389]:
np.split(x, [3, 5, 8])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1]), array([1, 2, 3])]

In [390]:
grid = np.arange(16).reshape((2, 8))
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [391]:
#along the vertical axis
upper, lower = np.vsplit(grid, [1])
print(upper)
print(lower)

[[0 1 2 3 4 5 6 7]]
[[ 8  9 10 11 12 13 14 15]]


In [392]:
#along the horizontal axis
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[0 1]
 [8 9]]
[[ 2  3  4  5  6  7]
 [10 11 12 13 14 15]]


### Iterating Over Arrays

5 by 3 array of random numbers 0-9: 

In [393]:
a = np.random.randint(0, 10, (5,3))
a

array([[4, 3, 4],
       [4, 8, 4],
       [3, 7, 5],
       [5, 0, 1],
       [5, 9, 3]])

In [394]:
#Iterate by row:
for row in a:
    print(row)

[4 3 4]
[4 8 4]
[3 7 5]
[5 0 1]
[5 9 3]


In [395]:
#column?
for column in np.transpose(a):
    print(column)

[4 4 3 5 5]
[3 8 7 0 9]
[4 4 5 1 3]


In [396]:
#Iterate by index:
for i in range(len(a)):
    print(a[i])

[4 3 4]
[4 8 4]
[3 7 5]
[5 0 1]
[5 9 3]


In [397]:
#Iterate by row using enumerate
list(enumerate(a))

[(0, array([4, 3, 4])),
 (1, array([4, 8, 4])),
 (2, array([3, 7, 5])),
 (3, array([5, 0, 1])),
 (4, array([5, 9, 3]))]

In [398]:
for i, row in enumerate(a):
    print('row', i, 'is', row)

row 0 is [4 3 4]
row 1 is [4 8 4]
row 2 is [3 7 5]
row 3 is [5 0 1]
row 4 is [5 9 3]


In [399]:
a2 = a**2
a2

array([[16,  9, 16],
       [16, 64, 16],
       [ 9, 49, 25],
       [25,  0,  1],
       [25, 81,  9]], dtype=int32)

In [400]:
#zip: iterate over multiple iterables.
list(zip(a))

[(array([4, 3, 4]),),
 (array([4, 8, 4]),),
 (array([3, 7, 5]),),
 (array([5, 0, 1]),),
 (array([5, 9, 3]),)]

In [401]:
for i, j in zip(a, a2):
    print(i,'+',j,'=',i+j)

[4 3 4] + [16  9 16] = [20 12 20]
[4 8 4] + [16 64 16] = [20 72 20]
[3 7 5] + [ 9 49 25] = [12 56 30]
[5 0 1] + [25  0  1] = [30  0  2]
[5 9 3] + [25 81  9] = [30 90 12]


## Operations

Use `+`, `-`, `*`, `/`,`**`... to perform element wise addition, subtraction, multiplication, division, etc.

In [402]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [403]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [404]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise division         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [405]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


In [406]:
print(y // x) # floor_divide
print(y % x) #remainder

[4 2 2]
[0 1 0]


**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [407]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [408]:
z = np.array([y, y**2, y**3])
print(z) # number of rows of array

[[  4   5   6]
 [ 16  25  36]
 [ 64 125 216]]


### Transposing arrays: permutes the dimensions of the array

In [409]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [410]:
z.shape

(2, 3)

In [411]:
#transpose:
np.transpose(z)

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [412]:
#alternatively, transpose using T:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [413]:
#the shape has changed:
z.T.shape

(3, 2)

In [414]:
#dtype to check the data type
z.dtype

dtype('int32')

In [415]:
#cast to a specific type
z2 = z.T.astype('f')
print(z2.dtype)
z2

float32


array([[ 4., 16.],
       [ 5., 25.],
       [ 6., 36.]], dtype=float32)

## Math Functions

Numpy has built-in math functions：

In [416]:
a = np.arange(-8,8,2).reshape(4,2)
a

array([[-8, -6],
       [-4, -2],
       [ 0,  2],
       [ 4,  6]])

In [417]:
print(a.sum())
#sum along the row/column axis
print(a.sum(0))
print(a.sum(1)) 

-8
[-8  0]
[-14  -6   2  10]


In [418]:
a.max()

6

In [419]:
a.min()

-8

In [420]:
a.mean()

-1.0

In [421]:
a.std()

4.58257569495584

In [422]:
#Return the index of the maximum and minimum values in the array.
a.argmax()

7

In [423]:
a.argmin()

0

In [424]:
##np.func() series
np.median(a)

-1.0

In [425]:
np.percentile(a,25) #25th percentile

-4.5

In [426]:
np.prod(a[1,]) #product of elements

8

In [427]:
print(np.any(a==0))
print(np.any(a==1))

True
False


In [428]:
print(np.all(a<8))

True


In [429]:
print(np.count_nonzero(a<3))

6


In [430]:
a

array([[-8, -6],
       [-4, -2],
       [ 0,  2],
       [ 4,  6]])

In [431]:
# alternatively
# False is interpreted as 0, and True is interpreted as 1
print(np.sum(a<3))
print(np.sum(a<3, axis = 1)) # along the column axis

6
[2 2 2 0]


In [432]:
#absolute values
print(abs(a)); print(np.abs(a));print(np.absolute(a))

[[8 6]
 [4 2]
 [0 2]
 [4 6]]
[[8 6]
 [4 2]
 [0 2]
 [4 6]]
[[8 6]
 [4 2]
 [0 2]
 [4 6]]


In [433]:
#trigonometric functions
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.arcsin([-1,0,1]))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[-1.57079633  0.          1.57079633]


In [434]:
#exponential and logarithms
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [435]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
exp(x) - 1 = [1.71828183e+00 6.38905610e+00 5.35981500e+01 2.20254658e+04]
log(1 + x) = [0.69314718 1.09861229 1.60943791 2.39789527]


In [436]:
?np.log

### Sorting

In [437]:
x = np.array([-4, 2, 3, 1, 5, 1])
y = x.copy().reshape(2,3)
print(x)
print(y)

[-4  2  3  1  5  1]
[[-4  2  3]
 [ 1  5  1]]


In [438]:
x.sort()
print(x)

y.sort(axis=0)
print(y)

[-4  1  1  2  3  5]
[[-4  2  1]
 [ 1  5  3]]


In [439]:
y.sort(axis=1)
print(y)

[[-4  1  2]
 [ 1  3  5]]


In [440]:
#reverse sorting
x[::-1].sort()
print(x)

[ 5  3  2  1  1 -4]


In [441]:
#return the index
x = np.array([-4, 2, 3, 1, 5, 1])
print(np.argsort(x))

[0 3 5 1 2 4]


In [442]:
x[np.argsort(x)]

array([-4,  1,  1,  2,  3,  5])

In [444]:
np.round?
