### Index alignment

### Series
The resulting array contains the union of indices of the two input arrays; <br>
Any item for which one or the other does not have an entry is marked with NaN, or "Not a Number".

In [101]:
import pandas as pd
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                    'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                    'New York': 19651127}, name='population')
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [102]:
# check on the indices
area.index | population.index

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/2582923136.py:2: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [103]:
area.index & population.index

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/884658361.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  area.index & population.index


Index(['Texas', 'California'], dtype='object')

In [104]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [105]:
area.index.intersection(population.index)

Index(['Texas', 'California'], dtype='object')

In [106]:
# another example:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, we can modify the fill value using appropriate object methods in place of the operators. For example, calling A.add(B) is equivalent to calling A + B, but allows optional explicit specification of the fill value for any elements in A or B that might be missing:

In [107]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### DataFrame

In [108]:
import pandas as pd
import numpy as np
A = pd.DataFrame(np.random.randint(0, 20, (2, 2)),
                    columns=list('AB'))
A

A   B
0  2  10
1  7  10

In [109]:
B = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                    columns=list('BAC'))
B

B  A  C
0  3  1  9
1  5  5  7
2  1  1  2

In [110]:
#indices are aligned correctly irrespective of their order
A + B

A     B   C
0   3.0  13.0 NaN
1  12.0  15.0 NaN
2   NaN   NaN NaN

In [111]:
Amean = A.stack().mean()
Amean

7.25

In [112]:
A.add(B,fill_value=Amean)

A      B      C
0   3.00  13.00  16.25
1  12.00  15.00  14.25
2   8.25   8.25   9.25

**Pandas methods** <br>
`+` add() <br>
`-` sub(), subtract() <br>
`*` mul(), multiply() <br>
`/` truediv(), div(), divide() <br>
`//` floordiv() <br>
`%` mod() <br>
`**` pow()

**Operations between Series and DataFrames**

In [113]:
A = np.random.randint(10, size=(3, 4))
print(A, '\n')
A - A[0]

[[1 1 1 2]
 [1 6 5 2]
 [0 3 7 2]] 



array([[ 0,  0,  0,  0],
       [ 0,  5,  4,  0],
       [-1,  2,  6,  0]])

In [114]:
# by default: operate on rows
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  1  1  1  2
1  1  6  5  2
2  0  3  7  2

In [115]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0  5  4  0
2 -1  2  6  0

In [116]:
# specify axis for column-wise operations
df.subtract(df['R'], axis=0)

Q  R  S  T
0  0  0  0  1
1 -5  0 -1 -4
2 -3  0  4 -1

In [117]:
df

Q  R  S  T
0  1  1  1  2
1  1  6  5  2
2  0  3  7  2

In [118]:
#automatically align indices
print(df.index)
halfrow = df.iloc[0, ::2]
halfrow

RangeIndex(start=0, stop=3, step=1)


Q    1
S    1
Name: 0, dtype: int32

In [119]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN  4.0 NaN
2 -1.0 NaN  6.0 NaN

### Pandas: Missing data

NaN , not a number, is a numeric data type used to represent any value that is undefined or unpresentable. <br>
It is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation. <br>
NaN is also assigned to variables, in a computation, that do not have values and have yet to be computed.

In [120]:
numbers = np.array([1, 2, None])
print(pd.Series(numbers))

0       1
1       2
2    None
dtype: object


In [121]:
#none returns error
# numbers.sum()

In [122]:
numbers = np.array([1, 2, np.nan])
print(pd.Series(numbers))

0    1.0
1    2.0
2    NaN
dtype: float64


In [123]:
#nan doesn't return errors, but not useful
numbers.sum()

nan

In [124]:
1 + np.nan

nan

In [125]:
0 * np.nan

nan

In [126]:
#use special aggregations
np.nansum(numbers), np.nanmin(numbers), np.nanmax(numbers)

(3.0, 1.0, 2.0)

One has to be mindful that in Python (and NumPy), the nan's don’t compare equal, but None's do. 

In [127]:
import numpy as np
np.nan == None

False

In [128]:
np.nan == np.nan

False

In [129]:
np.isnan(np.nan)

True

### NaN in Pandas
For types that don’t have an available sentinel value, Pandas automatically type-casts when NA values are present. <br>
If we set a value in an integer array to np.nan, it will automatically be upcast to a floating-point type to accommodate the NA. <br>

In [130]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [131]:
x = pd.Series(range(2), dtype=int)
print(x)

0    0
1    1
dtype: int32


In [132]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

**Pandas handing NAs by type** <br>
floating **No change** np.nan <br>
object **No change** None or np.nan <br>
integer **Cast to float64** np.nan <br>
boolean **Cast to object** None or np.nan <br>

### Operation on Null Values

**isnull()** <br>
Generate a Boolean mask indicating missing values<br>
**notnull()**<br>
Opposite of isnull()<br>
**dropna()**<br>
Return a filtered version of the data<br>
**fillna()**<br>
Return a copy of the data with missing values filled or imputed<br>

In [133]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [134]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [135]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [136]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [137]:
data.dropna()

0        1
2    hello
dtype: object

In [138]:
df = pd.DataFrame([[1, np.nan, 2],
[2, 3, 5],
[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [139]:
#dropna() will drop all rows in which 
#any null value is present:
df.dropna()

0    1  2
1  2.0  3.0  5

In [140]:
df.dropna(axis='columns') #or axis = 1

2
0  2
1  5
2  6

In [141]:
##default is any NA present
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [142]:
# change to how = 'all'
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [143]:
# thresh: require at least n non-null values
df.dropna(axis='rows', thresh=3)
# the number of non-null values fewer than 3 will be removed

0    1  2   3
1  2.0  3.0  5 NaN

**Fill null values**

In [144]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [145]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [146]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [147]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [148]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [149]:
df.fillna(method='bfill', axis=1)

0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

### MultiIndex

In [150]:
index = [('California', '2000'), ('California', '2010'),
            ('New York', '2000'), ('New York', '2010'),
            ('Texas', '2000'), ('Texas', '2010')]
populations = [33871648, 37253956,
                18976457, 19378102,
                20851820, 25145561]
# NOT recommended
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [151]:
pop[[i for i in pop.index if i[1]=='2010']]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [152]:
# Pandas MultiIndex
index = pd.MultiIndex.from_tuples(index)
pop2 = pd.Series(populations, index=index)
pop2

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [153]:
# reindex also works
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [154]:
# selection based on index, i.e. 2010
pop[:, '2010']

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [155]:
##extra dimension to a conventionally indexed DataFrame
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [156]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### MultiIndex Creation

In [157]:
#pass a list of two or more index arrays
df = pd.DataFrame(np.random.rand(4, 2),
                    index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                    columns=['data1', 'data2'])
df

data1     data2
a 1  0.170475  0.776561
  2  0.770494  0.009344
b 1  0.912919  0.177707
  2  0.066933  0.472662

In [158]:
#pass a dictionary with appropriate tuples as keys
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

#### Construct MultiIndex

In [159]:
#array
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [160]:
#tuple
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [161]:
#product
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [162]:
#MultiIndex with names: keep track of the meaning of index values
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### MultiIndex for Columns

In [163]:
# hierarchical indices
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                    names=['year', 'visit'])
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [164]:
# hierarchical columns
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], 
                                      ['HR', 'Temp']],
                                    names=['subject', 'type'])
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [165]:
# mock some data
data = np.round(np.random.randn(4, 6), 1) #standard normal; round to 0.1
data

array([[ 0.3,  1. ,  1.1,  0.5,  2. ,  1.3],
       [ 0.1,  0.7, -1. ,  0.5,  0.5, -0. ],
       [ 0.9, -0.5,  0.1,  1.3, -0.1,  0.3],
       [ 1.5, -0.8, -0.9, -1.1, -1.8, -2. ]])

In [166]:
data[:, ::2] *= 10
data += 37
data

array([[40. , 38. , 48. , 37.5, 57. , 38.3],
       [38. , 37.7, 27. , 37.5, 42. , 37. ],
       [46. , 36.5, 38. , 38.3, 36. , 37.3],
       [52. , 36.2, 28. , 35.9, 19. , 35. ]])

In [167]:
# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  38.0  48.0  37.5  57.0  38.3
     2      38.0  37.7  27.0  37.5  42.0  37.0
2014 1      46.0  36.5  38.0  38.3  36.0  37.3
     2      52.0  36.2  28.0  35.9  19.0  35.0

#### Indexing and Slicing

For Series:

In [168]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [169]:
pop['California', '2000']

33871648

In [170]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [171]:
# perform partial indexing on lower levels by passing an
# empty slice in the first index
pop[:, '2000'] 

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [172]:
# selection based on Boolean
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [173]:
# fancy indexing
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

#### For DataFrame:

In [174]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      40.0  38.0  48.0  37.5  57.0  38.3
     2      38.0  37.7  27.0  37.5  42.0  37.0
2014 1      46.0  36.5  38.0  38.3  36.0  37.3
     2      52.0  36.2  28.0  35.9  19.0  35.0

In [175]:
health_data['Guido', 'HR']

year  visit
2013  1        48.0
      2        27.0
2014  1        38.0
      2        28.0
Name: (Guido, HR), dtype: float64

In [176]:
#loc, iloc, ix
health_data.iloc[:2, 2:4]

subject    Guido      
type          HR  Temp
year visit            
2013 1      48.0  37.5
     2      27.0  37.5

In [177]:
# building the desired slice explicitly using an IndexSlice
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      40.0  48.0  57.0
2014 1      46.0  38.0  36.0

#### Rearranging Multi_indices

In [178]:
# data example
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]],
                                    names=['char', 'int'])
data = pd.Series(np.random.rand(6), index=index)
#alternative way to specify index names
#data.index.names = ['char', 'int'] 
data

char  int
a     1      0.096760
      2      0.223900
c     1      0.091833
      2      0.240507
b     1      0.142777
      2      0.689201
dtype: float64

In [179]:
#does not work for unsorted index
# data['a':'b']

In [180]:
# sorting
data = data.sort_index()
data

char  int
a     1      0.096760
      2      0.223900
b     1      0.142777
      2      0.689201
c     1      0.091833
      2      0.240507
dtype: float64

In [181]:
#now working
data['a':'b']

char  int
a     1      0.096760
      2      0.223900
b     1      0.142777
      2      0.689201
dtype: float64

#### stacking and unstacking

In [182]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [183]:
pop.unstack(level=0) #specify the level

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [184]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [185]:
pop.unstack(level=1).stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Index setting and resetting

In [186]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

reset_index: turn the index labels into columns;<br>
result in a DataFrame with columns holding the information that was formerly in the index. 

In [187]:
#optionally specify the name of the data for the column representation
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [188]:
#on the other hand
#build a MultiIndex from the column values
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

#### Data Aggregation

In [189]:
# name the index level
health_data.mean(level='year')

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/311171639.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  health_data.mean(level='year')


subject   Bob        Guido         Sue       
type       HR   Temp    HR  Temp    HR   Temp
year                                         
2013     39.0  37.85  37.5  37.5  49.5  37.65
2014     49.0  36.35  33.0  37.1  27.5  36.15

In [190]:
#axis=1: columns
health_data.mean(axis=1, level='type')

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/2045432079.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  health_data.mean(axis=1, level='type')


type               HR       Temp
year visit                      
2013 1      48.333333  37.933333
     2      35.666667  37.400000
2014 1      40.000000  37.366667
     2      33.000000  35.700000

In [191]:
#frist year then type
health_data.mean(level='year').mean(axis=1, level='type')

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/1087433296.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  health_data.mean(level='year').mean(axis=1, level='type')


type    HR       Temp
year                 
2013  42.0  37.666667
2014  36.5  36.533333

In [192]:
#first type then year: same
health_data.mean(axis=1, level='type').mean(level='year')

C:\Users\Hakurei\AppData\Local\Temp/ipykernel_16812/1604309361.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  health_data.mean(axis=1, level='type').mean(level='year')


type    HR       Temp
year                 
2013  42.0  37.666667
2014  36.5  36.533333